# Parameters:
#   KeyName:
#     Description: The EC2 Key Pair to allow SSH access to the instance
#     Type: 'AWS::EC2::KeyPair::RM-KP-1'
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: "eu-west-2c"

      BlockDeviceMappings:
        # Root volume
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 200
            VolumeType: gp3
        # Secondary volume
        - DeviceName: "xvdf"
          Ebs:
            VolumeSize: 100
            VolumeType: gp3

      InstanceType: "t3.medium"
      SubnetId: "subnet-083f3ffaafbbf9e90"
      SecurityGroupIds:
        - sg-08fec4972b48584b7
        - sg-0a1414ba1e20a015b
        - sg-047ad98317f2a7670
        - sg-063b929ac771da0ca
      KeyName: 'RM-KP-1' #!Ref KeyName
      # Image ref to be used as base
      ImageId: ami-00ffeb610527f540b # Windows 2022  #ami-0505148b3591e4c07 # Linux
      Tags:
        # EC2 Tags
        ## Set Name of EC2 Node
        - Key: Name
          Value: "My First CF Node" # Can this be an Octo var?
        ##Additional Tags
        - Key: Environment
          Value: "PPE"
        - Key: Schedule
          Value: "ppe-schedule"
